### ISSUE TITLE
Error on installation attempt

### ISSUE THREAD

**Issue by pellul** [RH12503/triangula-cli#3]
Hello, 
Thanks for sharing your work.

I am having trouble during the installation of the CLI, here are the outputs I get:

```text
go get -u github.com/RH12503/Triangula-CLI/triangula
# github.com/RH12503/Triangula-CLI/utils
go/src/github.com/RH12503/Triangula-CLI/utils/util.go:17:17: error: expected struct, slice, array,
or map type for composite literal
   17 |   return image2.Data{}, err
      |                 ^
go/src/github.com/RH12503/Triangula-CLI/utils/util.go:26:17: error: expected struct, slice, array,
or map type for composite literal
   26 |   return image2.Data{}, err
      |  
```

Am I missing something? 

Thanks

**Comment by rh12503** [comment]
Thanks for reporting this! Looks like I forgot to update the cli to the new api, I’ll try to fix this in a bit.

**Comment by rh12503** [comment]
I forgot to reference this issue, but it should be fixed with the latest commit!

**Comment by pellul** [comment]
It works like a charm, thanks.
